sudo: false

language: node_js

node_js:
  - lts/*

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

# install:
#   - yarn

script:
  - yarn build
# # https://docs.travis-ci.com/user/deployment/pages/
# deploy:
#   provider: pages
#   skip_cleanup: true
#   keep_history: true
#   github_token: $GITHUB_TOKEN
#   local_dir: public
#   # repo: zce.github.io
#   # target_branch: master

# # https://docs.travis-ci.com/user/deployment/surge/
# deploy:
#   provider: surge
#   skip_cleanup: true
#   project: public
#   domain: zce.surge.sh
