type Meta {
  # title: String
  # description: String
  # keywords: [String]
  key: String!
  value: String
}

type Social {
  weibo: String
  wechat: String
  qq: String
  zhihu: String
  github: String
  medium: String
  twitter: String
  facebook: String
}

type Author implements Node @dontInfer {
  name: String!
  slug: String!
  email: String!
  avatar: File @fileByRelativePath
  cover: File @fileByRelativePath
  bio: String
  website: String
  location: String
  social: Social,
  meta: [Meta]
  type: String!
  template: String!
  permalink: String!
  posts: [MarkdownRemark] @link(by: "fields.authors.name", from: "name")
}

type Category implements Node @dontInfer {
  name: String!
  slug: String!
  description: String
  cover: File @fileByRelativePath
  private: Boolean
  meta: [Meta]
  type: String!
  template: String!
  permalink: String!
  posts: [MarkdownRemark] @link(by: "fields.categories.name", from: "name")
}

type Tag implements Node @dontInfer {
  name: String!
  slug: String!
  description: String
  cover: File @fileByRelativePath
  private: Boolean
  meta: [Meta]
  type: String!
  template: String!
  permalink: String!
  posts: [MarkdownRemark] @link(by: "fields.tags.name", from: "name")
}

type Link implements Node @dontInfer {
  text: String!
  link: String!
  icon: File @fileByRelativePath
  target: String
  rel: String
}

type Fields {
  type: String!
  template: String!
  permalink: String!
  title: String!
  slug: String!
  date: Date @dateformat
  updated: Date @dateformat
  cover: File @fileByRelativePath
  description: String
  draft: Boolean
  private: Boolean
  featured: Boolean
  comment: Boolean
  authors: [Author] @link(by: "name")
  categories: [Category] @link(by: "name")
  tags: [Tag] @link(by: "name")
  meta: [Meta]
}

type Frontmatter {
  title: String!
  slug: String
  date: Date @dateformat
  updated: Date @dateformat
  cover: File @fileByRelativePath
  description: String
  draft: Boolean
  private: Boolean
  featured: Boolean
  comment: Boolean
  authors: [Author] @link(by: "name")
  categories: [Category] @link(by: "name")
  tags: [Tag] @link(by: "name")
  meta: [Meta]
}

type MarkdownRemark implements Node @donInfer {
  fields: Fields,
  frontmatter: Frontmatter
}

# (formatString: "YYYY-MM-DDTHH:mm:ssZ")
