# https://github.com/hexojs/hexo-starter/blob/master/_config.yml

url: https://blog.zce.me # no trailing slash!

name: Lei’s
title: Lei’s Personal Website
description: Thoughts, stories and ideas. (Developing, coming)
slogan: MAKE IT BETTER!
keywords: [zce, blog, personal, homepage]

author:
  name: Lei Wang
  email: w@zce.me
  url: https://zce.me

language: en

# inline svg instead
# logo: images/logo.svg
cover: images/cover.jpg

navigation:
  - text: Home
    link: /
  - text: Blog
    link: /blog/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Discuss
    link: /discuss/

socials:
  - name: Twitter
    link: https://twitter.com/w_zce
  - name: Facebook
    link: https://www.facebook.com/zccce
  - name: LinkedIn
    link: https://www.linkedin.com/in/zceme
  - name: GitHub
    link: https://github.com/zce
  - name: YouTube
    link: https://www.youtube.com/channel/UCFUwWB0v2qYqLaB95z1nv9Q
  - name: Weibo
    link: https://weibo.com/zceme
  - name: Weixin
    link: https://img.zce.me/wechat.jpg
  - name: QQ
    link: ~
  - name: Youku
    link: https://i.youku.com/zcezce
  - name: Bilibili
    link: https://space.bilibili.com/210242179

links:
  - text: Story
    link: /story/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Archive
    link: /archive/
  - text: Privacy
    link: /privacy-policy/
  - text: Terms
    link: /terms-of-service/

subscription:
  name: ITBetter
  qrcode: images/qrcode-wedn.jpg
  link: ~

card:
  image: images/unknown.jpg

disqus:
  shortname: zce-sandbox
