# https://github.com/hexojs/hexo-starter/blob/master/_config.yml

url: https://blog.zce.me # no trailing slash!

name: Lei’s
title: 汪磊的个人网站
description: 正在开发中，敬请期待
slogan: MAKE IT BETTER!
keywords:
  - 博客
  - 学习
  - 课程
  - 个人主页
  - 汪磊
  - zce.me
  - zce

author:
  name: 汪磊
  email: w@zce.me
  url: https://zce.me

# logo: images/logo.svg # inline svg instead
cover: images/cover.jpg

navigation:
  - text: 首页
    link: /
  - text: 课程
    link: /courses/
  - text: 博客
    link: /blog/
  - text: 关于
    link: /about/
  - text: 联系
    link: /contact/
  - text: 讨论
    link: /discuss/

socials:
  - name: 推特
    icon: twitter
    link: https://twitter.com/w_zce
  - name: 脸书
    icon: facebook
    link: https://www.facebook.com/zccce
  - name: 领英
    icon: linkedin
    link: https://www.linkedin.com/in/zceme
  - name: GitHub
    icon: github
    link: https://github.com/zce
  - name: 油管
    icon: youtube
    link: https://www.youtube.com/channel/UCFUwWB0v2qYqLaB95z1nv9Q
  - name: 微博
    icon: weibo
    link: https://weibo.com/zceme
  - name: 微信
    icon: weixin
    link: https://img.zce.me/wechat.jpg
  - name: QQ
    icon: qq
    link: http://wpa.qq.com/msgrd?v=3&uin=27102514&site=qq&menu=yes
  - name: 哔哩哔哩
    icon: bilibili
    link: https://space.bilibili.com/210242179
  - name: 优酷
    icon: youku
    link: https://i.youku.com/zcezce

links:
  - text: 故事
    link: /story/
  - text: 关于我们
    link: /about/
  - text: 联系我们
    link: /contact/
  - text: 全部分类
    link: /categories/
  - text: 内容归档
    link: /archive/
  - text: 实验室
    link: /labs/
  # - text: 隐私策略
  #   link: /privacy-policy/
  # - text: 服务条款
  #   link: /terms-of-service/

subscription:
  name: ITBetter
  qrcode: https://img.zce.me/qrcode/itbetter.jpg
