# https://github.com/hexojs/hexo-starter/blob/master/_config.yml

url: https://beta.zce.me # no trailing slash!

name: Lei’s
title: Lei’s Personal Website
description: In development, coming soon. # Thoughts, stories and ideas.
slogan: MAKE IT BETTER!
keywords:
  - Course
  - Blog
  - Homepage
  - Personal
  - 汪磊
  - zce.me
  - zce

author:
  name: Lei Wang
  email: w@zce.me
  url: https://zce.me

# logo: images/logo.svg # inline svg instead
cover: images/cover.jpg

navigation:
  - text: Home
    link: /
  - text: Courses
    link: /courses/
  - text: Blog
    link: /blog/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Discuss
    link: /discuss/

socials:
  - name: Twitter
    link: https://twitter.com/w_zce
  - name: Facebook
    link: https://www.facebook.com/zccce
  - name: LinkedIn
    link: https://www.linkedin.com/in/zceme
  - name: GitHub
    link: https://github.com/zce
  - name: YouTube
    link: https://www.youtube.com/channel/UCFUwWB0v2qYqLaB95z1nv9Q
  - name: Weibo
    link: https://weibo.com/zceme
  - name: Weixin
    link: https://img.zce.me/wechat.jpg
  - name: QQ
    link: ~
  - name: Bilibili
    link: https://space.bilibili.com/210242179
  - name: Youku
    link: https://i.youku.com/zcezce

links:
  - text: Story
    link: /story/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Categories
    link: /categories/
  - text: Archive
    link: /archive/
  - text: Labs
    link: /labs/
  # - text: Privacy
  #   link: /privacy-policy/
  # - text: Terms
  #   link: /terms-of-service/

subscription:
  name: ITBetter
  qrcode: images/qrcode-wedn.jpg
