# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Beta Deploy

on:
  release:
    types:
      # - created
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Format Source
        run: npm run format

      - name: Build Site
        run: npm run release
        env:
          NODE_ENV: production
          GATSBY_BAIDU_ID: b03089dd45bcef4ab4be511dce81dbc8
          CI: true

      - name: Deploy to Coding
        run: npx gh-pages
          -d public -t
          -r https://${{secrets.CODING_TOKEN}}@e.coding.net/zce/zce.me/beta.git
          -b master
          -u "GitHub Actions <bots@github.com>"
          -f
