# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: CI

on: push

# on:
#   release:
#     types:
#       - published
#       # - created
#       # - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm install
      - name: Format Source
        run: npm run format
      - name: Build Site
        run: npm run release
        env:
          NODE_ENV: production
          CI: true
      # use ZEIT Now instead
      # - name: Deploy (Nightly)
      #   if: github.ref == 'refs/heads/master'
      #   run: npx surge
      #     public
      #     zce.surge.sh
      #     --token ${{secrets.SURGE_TOKEN}}
      # - name: Deploy (Nightly)
      #   if: github.ref == 'refs/heads/master'
      #   run: npx gh-pages
      #     -d public -b master -u "GitHub Actions <bots@github.com>" -t -f
      #     -r https://${{secrets.CODING_TOKEN}}@e.coding.net/zce/zce.me/nightly.git
      # - name: Deploy (Beta)
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: npx gh-pages
      #     -d public -b master -u "GitHub Actions <bots@github.com>" -t -f
      #     -r https://${{secrets.CODING_TOKEN}}@e.coding.net/zce/zce.me/beta.git
      # - name: Deploy (Stable)
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: npx gh-pages
      #     -d public -b master -u "GitHub Actions <bots@github.com>" -t
      #     -r https://${{secrets.CODING_TOKEN}}@e.coding.net/zce/zce.me.git
