# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Stable Deploy

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn

      - name: Format Source
        run: yarn format

      - name: Build Site
        run: yarn dist
        env:
          NODE_ENV: production
          GATSBY_BAIDU_ID: ebba0e1e4fd2aeae212a8de341d8e1bb
          CI: true

      - name: Deploy to Coding
        run: npx gh-pages
          -d public
          -r https://${{secrets.CODING_TOKEN}}@git.dev.tencent.com/zce/blog.zce.me.git
          -b master
          -u "GitHub Actions <bots@github.com>"
